name: Deploy Frontend Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kode Frontend
        uses: actions/checkout@v3

      - name: Deploy ke VM Frontend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FRONTEND_SSH_HOST }}
          username: ${{ secrets.FRONTEND_SSH_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          port: 22
          script: |
            echo "Masuk ke VM Frontend"
            cd /home/pbluser/frontend-genzett
            git pull origin main
            docker compose down
            docker compose up -d --build
