name: Deploy Frontend GenZett to VM

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload source code to VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/Frontend-GenZett"
          strip_components: 0

      - name: SSH and Redeploy Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Frontend-GenZett

            # Optional: Pull latest changes if needed (only if your repo is cloned in VM)
            # git pull origin development

            # Optional: Stop running containers gracefully
            docker compose down || true

            # Build and deploy again
            docker compose build --no-cache
            docker compose up -d --force-recreate
